### ISSUE TITLE
framelayout_demo.xml missing

### ISSUE THREAD

**Issue by greldinard** [tkuenneth/begleitmaterialien-zu-android-11#1]
In Kapitel 5.1.2 wird auf die framelayout_demo.xml verwiesen. Diese bedindet sich jedoch nicht wie beschrieben in der App WidgetDemo, sondern in der App LeeresProjekt im Ordner kapitel_04. Da ist irgendwas schief gelaufen.

**Comment by greldinard** [comment]
Es wird auf die Datei verwiesen bevor verraten wird wo sie sich befindet... Daher nicht sehr schwerwiegend - dennoch verwirrend.

**Comment by tkuenneth** [comment]
Auf jeden Fall vielen Dank für den Hinweis. Ich schau mir das nochmal genauer an und gebe einen entsprechenden Hinweis an den Verlag für die "Errata-Liste"
